baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "Learn"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "blue"

